"""Bake the package version from the latest git tag into quipu/_build_version.py.

Usage:
    python scripts/bake_version.py

Version source: ``git describe --tags --abbrev=0`` in the repo root.
    A tag like ``v0.3.0`` or ``0.3.0`` yields version ``0.3.0``.
    If no tag exists, falls back to ``0.0.0`` with a LOUD warning.

Writes:
    quipu/_build_version.py   (DO NOT COMMIT — gitignored)
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_OUT_PATH = _REPO_ROOT / "quipu" / "_build_version.py"

_VERSION_RE = re.compile(r"^\d+\.\d+\.\d+$")

_OUT_TEMPLATE = (
    "# AUTO-GENERATED by scripts/bake_version.py -- DO NOT EDIT, DO NOT COMMIT.\n"
    '__version__ = "{version}"\n'
)

_FALLBACK_VERSION = "0.0.0"


def parse_tag_version(describe_output: str) -> str:
    """Parse a git-describe or git-tag output string into a bare X.Y.Z string.

    Handles:
      ``v0.3.0``           -> ``0.3.0``
      ``0.3.0``            -> ``0.3.0``
      ``v0.3.0-2-gabcdef`` -> ``0.3.0``

    Raises ``ValueError`` if no valid X.Y.Z can be extracted.
    """
    raw = describe_output.strip()
    if raw.lower().startswith("v"):
        raw = raw[1:]
    bare = raw.split("-")[0]
    if not _VERSION_RE.match(bare):
        raise ValueError(
            f"cannot parse X.Y.Z from git describe output: {describe_output!r}"
        )
    return bare


def _get_version_from_git() -> str:
    """Run ``git describe --tags --abbrev=0`` and parse the result.

    Returns the bare X.Y.Z string on success, or ``0.0.0`` with a warning.
    """
    try:
        result = subprocess.run(
            ["git", "describe", "--tags", "--abbrev=0"],
            cwd=str(_REPO_ROOT),
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as exc:
        print(
            f"[bake_version] WARNING: git not available or timed out ({exc}). "
            f"Falling back to version {_FALLBACK_VERSION}.",
            flush=True,
        )
        return _FALLBACK_VERSION

    if result.returncode != 0:
        print(
            "[bake_version] WARNING: git describe --tags --abbrev=0 failed "
            f"(exit {result.returncode}; stderr: {result.stderr.strip()!r}). "
            "No git tags found? Tag the release first: git tag vX.Y.Z. "
            f"Falling back to version {_FALLBACK_VERSION}.",
            flush=True,
        )
        return _FALLBACK_VERSION

    describe_output = result.stdout.strip()
    try:
        version = parse_tag_version(describe_output)
    except ValueError as exc:
        print(
            f"[bake_version] WARNING: {exc}. "
            f"Falling back to version {_FALLBACK_VERSION}.",
            flush=True,
        )
        return _FALLBACK_VERSION

    return version


def main() -> None:
    version = _get_version_from_git()

    _OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUT_PATH.write_text(_OUT_TEMPLATE.format(version=version), encoding="utf-8")
    print(
        f"[bake_version] Baked __version__={version} into {_OUT_PATH}",
        flush=True,
    )


if __name__ == "__main__":
    main()
